from typing import Optional, List, Protocol
from ..blocks import MemoryBlock


class StorageBackend(Protocol):
    async def save(self, memory: MemoryBlock, tier: str = "long_term") -> bool:
        ...
    async def load(self, memory_id: str) -> Optional[MemoryBlock]:
        ...
    async def delete(self, memory_id: str) -> bool:
        ...
    async def search(self, query: str, limit: int = 10, tier: Optional[str] = None) -> List[MemoryBlock]:
        ...
    async def list_all(self, limit: int = 100, offset: int = 0, tier: Optional[str] = None) -> List[MemoryBlock]:
        ...
    async def list_by_tier(self, tier: str, limit: int = 10000, offset: int = 0) -> List[MemoryBlock]:
        ...
    async def delete_by_tier(self, tier: str) -> int:
        ...
    async def count_by_tier(self, tier: str) -> int:
        ...
    async def delete_by_session_and_tier(self, session_id: str, tier: str) -> int:
        ...
    async def delete_by_user_and_tier(self, user_id: str, tier: str) -> int:
        ...
    async def clear(self) -> bool:
        ...
